class_name WheelLevels
extends Object

## Themed wheel-course definitions. Wheel style (size/roundness) changes what's viable.

const LEVELS := {
	&"gap_gorge": {
		"title": "Gap Gorge",
		"blurb": "Jump pads + wide chasms. Draw BIG wheels.",
		"icon": "res://assets/sprites/portal_icons/gap_gorge.png",
		"sky": Color(0.45, 0.62, 0.88),
		"ground": Color(0.42, 0.5, 0.28),
		"seed": 101,
		"course_length": 7800.0,
		"scroll_speed": 88.0,
		"gap_min": 280.0,
		"gap_max": 420.0,
		"stretch_min": 360.0,
		"stretch_max": 560.0,
		"platform_count": 34,
		"rock_count": 8,
		"ceiling_count": 4,
		"ceiling_y_min": 40.0,
		"ceiling_y_max": 90.0,
		"peel_count": 12,
		"banana_count": 40,
		"want_size_min": 0.62,
		"want_size_max": 1.0,
		"want_round_min": 0.0,
		"jump_size_boost": 1.0,
		"small_size_jump_penalty": 0.55,
		"accel_size_factor": 0.35,
		"bumpy": 0.0,
		"icy": 0.0,
		"pattern": &"gorge",
		"theme_tip": "Pads + wide gaps — big wheels clear the leaps.",
	},
	&"needle_pass": {
		"title": "Needle Pass",
		"blurb": "Spike tunnels + saws. Tiny wheels fit the ship-lane.",
		"icon": "res://assets/sprites/portal_icons/needle_pass.png",
		"sky": Color(0.22, 0.28, 0.34),
		"ground": Color(0.35, 0.38, 0.32),
		"seed": 202,
		"course_length": 7200.0,
		"scroll_speed": 100.0,
		"gap_min": 110.0,
		"gap_max": 180.0,
		"stretch_min": 380.0,
		"stretch_max": 620.0,
		"platform_count": 10,
		"rock_count": 14,
		"ceiling_count": 26,
		"ceiling_y_min": 300.0,
		"ceiling_y_max": 360.0,
		"peel_count": 18,
		"banana_count": 35,
		"want_size_min": 0.0,
		"want_size_max": 0.42,
		"want_round_min": 0.0,
		"jump_size_boost": 0.15,
		"small_size_jump_penalty": 0.0,
		"accel_size_factor": 0.55,
		"bumpy": 0.1,
		"icy": 0.0,
		"pattern": &"tunnel",
		"theme_tip": "Floor+ceiling spikes — stay short or get shredded.",
	},
	&"wobble_ridge": {
		"title": "Wobble Ridge",
		"blurb": "Moving platforms, saws, chaos. Round wheels hold the line.",
		"icon": "res://assets/sprites/portal_icons/wobble_ridge.png",
		"sky": Color(0.55, 0.48, 0.32),
		"ground": Color(0.5, 0.4, 0.22),
		"seed": 303,
		"course_length": 8000.0,
		"scroll_speed": 92.0,
		"gap_min": 130.0,
		"gap_max": 210.0,
		"stretch_min": 280.0,
		"stretch_max": 480.0,
		"platform_count": 22,
		"rock_count": 28,
		"ceiling_count": 6,
		"ceiling_y_min": 80.0,
		"ceiling_y_max": 140.0,
		"peel_count": 28,
		"banana_count": 45,
		"want_size_min": 0.25,
		"want_size_max": 0.85,
		"want_round_min": 0.7,
		"jump_size_boost": 0.35,
		"small_size_jump_penalty": 0.15,
		"accel_size_factor": 0.25,
		"bumpy": 1.0,
		"icy": 0.0,
		"pattern": &"chaos",
		"theme_tip": "Movers + saws — round wheels stop the wobble.",
	},
	&"sprint_delta": {
		"title": "Sprint Delta",
		"blurb": "Fast scroll, tight spike rhythm. Compact wheels keep up.",
		"icon": "res://assets/sprites/portal_icons/sprint_delta.png",
		"sky": Color(0.3, 0.55, 0.5),
		"ground": Color(0.28, 0.48, 0.38),
		"seed": 404,
		"course_length": 9000.0,
		"scroll_speed": 145.0,
		"gap_min": 160.0,
		"gap_max": 260.0,
		"stretch_min": 400.0,
		"stretch_max": 700.0,
		"platform_count": 24,
		"rock_count": 16,
		"ceiling_count": 8,
		"ceiling_y_min": 70.0,
		"ceiling_y_max": 130.0,
		"peel_count": 20,
		"banana_count": 50,
		"want_size_min": 0.0,
		"want_size_max": 0.5,
		"want_round_min": 0.35,
		"jump_size_boost": 0.4,
		"small_size_jump_penalty": 0.1,
		"accel_size_factor": 0.75,
		"bumpy": 0.2,
		"icy": 0.0,
		"pattern": &"sprint",
		"theme_tip": "Spike chains under a fast scroll — stay compact.",
	},
	&"frost_fjord": {
		"title": "Frost Fjord",
		"blurb": "Ice + pads + frozen saws. Round medium wheels grip.",
		"icon": "res://assets/sprites/portal_icons/frost_fjord.png",
		"sky": Color(0.62, 0.78, 0.92),
		"ground": Color(0.55, 0.42, 0.34),
		"seed": 505,
		"course_length": 8200.0,
		"scroll_speed": 105.0,
		"gap_min": 190.0,
		"gap_max": 310.0,
		"stretch_min": 340.0,
		"stretch_max": 580.0,
		"platform_count": 26,
		"rock_count": 18,
		"ceiling_count": 10,
		"ceiling_y_min": 60.0,
		"ceiling_y_max": 120.0,
		"peel_count": 10,
		"banana_count": 42,
		"want_size_min": 0.4,
		"want_size_max": 0.75,
		"want_round_min": 0.72,
		"jump_size_boost": 0.45,
		"small_size_jump_penalty": 0.25,
		"accel_size_factor": 0.2,
		"bumpy": 0.15,
		"icy": 1.0,
		"pattern": &"frost",
		"theme_tip": "Slippery ice into saws — round wheels stick the landings.",
	},
}


static func ids() -> Array[StringName]:
	var out: Array[StringName] = []
	for k in LEVELS.keys():
		out.append(k)
	return out


static func get_level(id: StringName) -> Dictionary:
	if LEVELS.has(id):
		return LEVELS[id]
	return LEVELS[&"gap_gorge"]


static func title_of(id: StringName) -> String:
	return str(get_level(id).get("title", "Wheel Trail"))
