class_name WheelLevels
extends Object

## Themed wheel-course definitions. Wheel style (size/roundness) changes what's viable.
## Every track has three vertical lanes (low / mid / high) plus ground stretches.

const LEVELS := {
	&"gap_gorge": {
		"title": "Gap Gorge",
		"blurb": "Jump pads + wide chasms. Draw BIG wheels.",
		"icon": "res://assets/sprites/portal_icons/gap_gorge.png",
		"sky": Color(0.45, 0.62, 0.88),
		"ground": Color(0.42, 0.5, 0.28),
		"seed": 101,
		"course_length": 7800.0,
		"scroll_speed": 88.0,
		"gap_min": 180.0,
		"gap_max": 280.0,
		"stretch_min": 340.0,
		"stretch_max": 520.0,
		"platform_count": 42,
		"platform_spacing": 400.0,
		"lane_low_y": 455.0,
		"lane_mid_y": 335.0,
		"lane_high_y": 210.0,
		"rock_count": 8,
		"ceiling_count": 4,
		"ceiling_y_min": 50.0,
		"ceiling_y_max": 110.0,
		"peel_count": 12,
		"banana_count": 40,
		"want_size_min": 0.62,
		"want_size_max": 1.0,
		"want_round_min": 0.0,
		"jump_size_boost": 1.0,
		"small_size_jump_penalty": 0.55,
		"accel_size_factor": 0.35,
		"bumpy": 0.0,
		"icy": 0.0,
		"pattern": &"gorge",
		"theme": &"forest",
		"theme_tip": "Pads + wide gaps — big wheels clear the leaps.",
	},
	&"needle_pass": {
		"title": "Needle Pass",
		"blurb": "Spike tunnels + saws. Tiny wheels fit the ship-lane.",
		"icon": "res://assets/sprites/portal_icons/needle_pass.png",
		"sky": Color(0.22, 0.28, 0.34),
		"ground": Color(0.35, 0.38, 0.32),
		"seed": 202,
		"course_length": 7200.0,
		"scroll_speed": 100.0,
		"gap_min": 120.0,
		"gap_max": 200.0,
		"stretch_min": 360.0,
		"stretch_max": 580.0,
		"platform_count": 36,
		"platform_spacing": 380.0,
		"lane_low_y": 455.0,
		"lane_mid_y": 335.0,
		"lane_high_y": 210.0,
		"rock_count": 10,
		"ceiling_count": 12,
		"ceiling_y_min": 60.0,
		"ceiling_y_max": 120.0,
		"peel_count": 18,
		"banana_count": 35,
		"want_size_min": 0.0,
		"want_size_max": 0.42,
		"want_round_min": 0.0,
		"jump_size_boost": 0.15,
		"small_size_jump_penalty": 0.0,
		"accel_size_factor": 0.55,
		"bumpy": 0.1,
		"icy": 0.0,
		"pattern": &"tunnel",
		"theme": &"forest",
		"theme_tip": "Floor+ceiling spikes — stay short or get shredded.",
	},
	&"wobble_ridge": {
		"title": "Wobble Ridge",
		"blurb": "Moving platforms, saws, chaos. Round wheels hold the line.",
		"icon": "res://assets/sprites/portal_icons/wobble_ridge.png",
		"sky": Color(0.55, 0.48, 0.32),
		"ground": Color(0.5, 0.4, 0.22),
		"seed": 303,
		"course_length": 8000.0,
		"scroll_speed": 92.0,
		"gap_min": 130.0,
		"gap_max": 210.0,
		"stretch_min": 280.0,
		"stretch_max": 460.0,
		"platform_count": 39,
		"platform_spacing": 390.0,
		"lane_low_y": 455.0,
		"lane_mid_y": 335.0,
		"lane_high_y": 210.0,
		"rock_count": 22,
		"ceiling_count": 6,
		"ceiling_y_min": 55.0,
		"ceiling_y_max": 115.0,
		"peel_count": 28,
		"banana_count": 45,
		"want_size_min": 0.25,
		"want_size_max": 0.85,
		"want_round_min": 0.7,
		"jump_size_boost": 0.35,
		"small_size_jump_penalty": 0.15,
		"accel_size_factor": 0.25,
		"bumpy": 1.0,
		"icy": 0.0,
		"pattern": &"chaos",
		"theme": &"forest",
		"theme_tip": "Movers + saws — round wheels stop the wobble.",
	},
	&"sprint_delta": {
		"title": "Sprint Delta",
		"blurb": "Fast scroll, tight spike rhythm. Compact wheels keep up.",
		"icon": "res://assets/sprites/portal_icons/sprint_delta.png",
		"sky": Color(0.3, 0.55, 0.5),
		"ground": Color(0.28, 0.48, 0.38),
		"seed": 404,
		"course_length": 9000.0,
		"scroll_speed": 145.0,
		"gap_min": 140.0,
		"gap_max": 220.0,
		"stretch_min": 380.0,
		"stretch_max": 640.0,
		"platform_count": 45,
		"platform_spacing": 390.0,
		"lane_low_y": 455.0,
		"lane_mid_y": 335.0,
		"lane_high_y": 210.0,
		"rock_count": 14,
		"ceiling_count": 8,
		"ceiling_y_min": 55.0,
		"ceiling_y_max": 120.0,
		"peel_count": 20,
		"banana_count": 50,
		"want_size_min": 0.0,
		"want_size_max": 0.5,
		"want_round_min": 0.35,
		"jump_size_boost": 0.4,
		"small_size_jump_penalty": 0.1,
		"accel_size_factor": 0.75,
		"bumpy": 0.2,
		"icy": 0.0,
		"pattern": &"sprint",
		"theme": &"forest",
		"theme_tip": "Spike chains under a fast scroll — stay compact.",
	},
	&"frost_fjord": {
		"title": "Frost Fjord",
		"blurb": "Ice + pads + frozen saws. Round medium wheels grip.",
		"icon": "res://assets/sprites/portal_icons/frost_fjord.png",
		"sky": Color(0.62, 0.78, 0.92),
		"ground": Color(0.55, 0.42, 0.34),
		"seed": 505,
		"course_length": 8200.0,
		"scroll_speed": 105.0,
		"gap_min": 150.0,
		"gap_max": 240.0,
		"stretch_min": 320.0,
		"stretch_max": 540.0,
		"platform_count": 39,
		"platform_spacing": 390.0,
		"lane_low_y": 455.0,
		"lane_mid_y": 335.0,
		"lane_high_y": 210.0,
		"rock_count": 16,
		"ceiling_count": 10,
		"ceiling_y_min": 50.0,
		"ceiling_y_max": 110.0,
		"peel_count": 10,
		"banana_count": 42,
		"want_size_min": 0.4,
		"want_size_max": 0.75,
		"want_round_min": 0.72,
		"jump_size_boost": 0.45,
		"small_size_jump_penalty": 0.25,
		"accel_size_factor": 0.2,
		"bumpy": 0.15,
		"icy": 1.0,
		"pattern": &"frost",
		"theme": &"winter",
		"theme_tip": "Slippery ice into saws — round wheels stick the landings.",
	},
	&"moon_graveyard": {
		"title": "Moon Graveyard",
		"blurb": "Stone tombs under a full moon. Medium wheels clear the crypt lanes.",
		"icon": "res://assets/sprites/moon_graveyard/Salt.png",
		"sky": Color(0.08, 0.1, 0.22),
		"ground": Color(0.28, 0.27, 0.24),
		"seed": 606,
		"course_length": 8000.0,
		"scroll_speed": 98.0,
		"gap_min": 160.0,
		"gap_max": 250.0,
		"stretch_min": 320.0,
		"stretch_max": 520.0,
		"platform_count": 42,
		"platform_spacing": 390.0,
		"lane_low_y": 455.0,
		"lane_mid_y": 335.0,
		"lane_high_y": 210.0,
		"rock_count": 6,
		"ceiling_count": 4,
		"ceiling_y_min": 40.0,
		"ceiling_y_max": 100.0,
		"peel_count": 14,
		"banana_count": 40,
		"want_size_min": 0.3,
		"want_size_max": 0.8,
		"want_round_min": 0.2,
		"jump_size_boost": 0.5,
		"small_size_jump_penalty": 0.2,
		"accel_size_factor": 0.3,
		"bumpy": 0.25,
		"icy": 0.0,
		"pattern": &"grave",
		"theme": &"graveyard",
		"theme_tip": "Stone platforms + hanging crypt spikes — keep your footing.",
	},
	&"desert_sky": {
		"title": "Desert Sky",
		"blurb": "Dune parallax and wide gaps. Round wheels hold the sand.",
		"icon": "res://assets/sprites/parallax_desert/shrine_emblem.png",
		"sky": Color(0.55, 0.72, 0.9),
		"ground": Color(0.72, 0.55, 0.32),
		"seed": 707,
		"course_length": 8600.0,
		"scroll_speed": 110.0,
		"gap_min": 170.0,
		"gap_max": 260.0,
		"stretch_min": 360.0,
		"stretch_max": 580.0,
		"platform_count": 39,
		"platform_spacing": 400.0,
		"lane_low_y": 455.0,
		"lane_mid_y": 335.0,
		"lane_high_y": 210.0,
		"rock_count": 8,
		"ceiling_count": 3,
		"ceiling_y_min": 40.0,
		"ceiling_y_max": 90.0,
		"peel_count": 16,
		"banana_count": 48,
		"want_size_min": 0.35,
		"want_size_max": 0.85,
		"want_round_min": 0.55,
		"jump_size_boost": 0.7,
		"small_size_jump_penalty": 0.3,
		"accel_size_factor": 0.4,
		"bumpy": 0.35,
		"icy": 0.0,
		"pattern": &"desert",
		"theme": &"desert",
		"theme_tip": "Wide dune gaps — round wheels stick the landings.",
	},
	&"lunar_void": {
		"title": "Lunar Void",
		"blurb": "Moonscape parallax, low gravity hops. Compact wheels fit the craters.",
		"icon": "res://assets/sprites/parallax_moon/shrine_emblem.png",
		"sky": Color(0.05, 0.06, 0.12),
		"ground": Color(0.35, 0.36, 0.4),
		"seed": 808,
		"course_length": 7800.0,
		"scroll_speed": 102.0,
		"gap_min": 150.0,
		"gap_max": 240.0,
		"stretch_min": 300.0,
		"stretch_max": 500.0,
		"platform_count": 42,
		"platform_spacing": 380.0,
		"lane_low_y": 455.0,
		"lane_mid_y": 335.0,
		"lane_high_y": 210.0,
		"rock_count": 10,
		"ceiling_count": 5,
		"ceiling_y_min": 40.0,
		"ceiling_y_max": 100.0,
		"peel_count": 12,
		"banana_count": 38,
		"want_size_min": 0.0,
		"want_size_max": 0.55,
		"want_round_min": 0.4,
		"jump_size_boost": 0.85,
		"small_size_jump_penalty": 0.05,
		"accel_size_factor": 0.5,
		"bumpy": 0.15,
		"icy": 0.15,
		"pattern": &"lunar",
		"theme": &"lunar",
		"theme_tip": "Low-grav hops between crater lanes — stay compact.",
	},
	&"tiger_chase": {
		"title": "Tiger Trail",
		"blurb": "A jungle sprint — a tiger slowly hunts you. Stay ahead.",
		"icon": "res://assets/sprites/tiger/shrine_emblem.png",
		"sky": Color(0.35, 0.62, 0.42),
		"ground": Color(0.32, 0.48, 0.24),
		"seed": 909,
		"course_length": 7600.0,
		"scroll_speed": 96.0,
		"gap_min": 140.0,
		"gap_max": 220.0,
		"stretch_min": 340.0,
		"stretch_max": 540.0,
		"platform_count": 40,
		"platform_spacing": 390.0,
		"lane_low_y": 455.0,
		"lane_mid_y": 335.0,
		"lane_high_y": 210.0,
		"rock_count": 12,
		"ceiling_count": 4,
		"ceiling_y_min": 50.0,
		"ceiling_y_max": 110.0,
		"peel_count": 14,
		"banana_count": 44,
		"want_size_min": 0.2,
		"want_size_max": 0.75,
		"want_round_min": 0.25,
		"jump_size_boost": 0.45,
		"small_size_jump_penalty": 0.15,
		"accel_size_factor": 0.4,
		"bumpy": 0.2,
		"icy": 0.0,
		"pattern": &"jungle",
		"theme": &"forest",
		"chase_tiger": true,
		"tiger_speed": 155.0,
		"theme_tip": "A tiger stalks you — keep rolling or get mauled.",
	},
}


static func ids() -> Array[StringName]:
	var out: Array[StringName] = []
	for k in LEVELS.keys():
		out.append(k)
	return out


static func get_level(id: StringName) -> Dictionary:
	if LEVELS.has(id):
		return LEVELS[id]
	return LEVELS[&"gap_gorge"]


static func title_of(id: StringName) -> String:
	return str(get_level(id).get("title", "Wheel Trail"))
